export const TILES_GENERATED = 'TILES_GENERATED'
export const RESET = 'RESET'
export const RUN = 'RUN'
export const RUNNING = ''
export const RETRY = 'RETRY'
export const SUCCESS = 'SUCCESS'
export const REFRESH = 'REFRESH'